name: transfermarkt-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.1.5=py38hb2f4e1b_0
  - kaggle==1.5.12
  - boto3==1.16.47
  - inflection=0.5.1=py38hecd8cb5_0
  - dvc[s3]==2.1.0
  - pip==21.0.1
  - pip:
      - frictionless==4.1.0
      - pycountry==20.7.3
      - docker==5.0.0
