name: transfermarkt-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - kaggle==1.5.12
  - boto3==1.16.47
  - dvc[s3]==2.1.0
  - pip==21.0.1
  - pip:
      - pandas==1.1.5
      - inflection==0.5.1
      - frictionless==4.1.0
      - pycountry==20.7.3
      - docker==5.0.0
